config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: [:new, :create, :destroy, :homepage] do
    collection do
      get :color
    end
  end

  root "pages#homepage"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id         :bigint           not null, primary key
#  color      :string
#  model      :string
#  year       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Car < ApplicationRecord
  validates :model, presence: true
  validates :year, presence: true, numericality: {only_integer: true, greater_than: 1900, less_than: 2021}

  has_many :variants, dependent: :destroy
  accepts_nested_attributes_for :variants, allow_destroy: true
end

app/models/variant.rb
# == Schema Information
#
# Table name: variants
#
#  id           :bigint           not null, primary key
#  fuel_type    :string
#  transmission :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  car_id       :bigint           not null
#
# Indexes
#
#  index_variants_on_car_id  (car_id)
#
# Foreign Keys
#
#  fk_rails_...  (car_id => cars.id)
#
class Variant < ApplicationRecord
  validates :fuel_type, presence: true, inclusion: {in: %w[petrol diesel electric]}
  validates :transmission, presence: true, inclusion: {in: %w[manual automatic]}

  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
    @car = Car.new
    @car.variants.build

    # get all different models from the car
    @models = Car.all.map(&:model).uniq
    @colors = Car.all.map(&:color).uniq
  end

  def create
    @car = Car.new(car_params)
    @car.variants.build(variant_params)
    @models = Car.all.map(&:model).uniq
    if @car.save
      redirect_to root_path
    else
      puts(@car.errors.full_messages)
      render :homepage
    end
  end

  def color
    brand = params[:brand]
    @colors = Car.where(model: brand).map(&:color).uniq
    @target = params[:target]
    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to root_path
  end

  private

  def car_params
    params.require(:car).permit(:model, :color, :year)
  end

  private

  def variant_params
    params.require(:variants_attributes).permit(:fuel_type, :transmission)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinStimulusExercises</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_variant_form.html.erb
<div>
<%= car_variant.check_box :_destroy %>
<%= car_variant.label "Fuel Type" %>
<%= car_variant.text_field :fuel_type  %>
<%= car_variant.label "Transmission" %>
<%= car_variant.text_field :Transmission %>
</div>

app/views/pages/color.turbo_stream.erb
<%= turbo_stream.update @target do %>
  <%= options_for_select @colors %>
<% end %>

app/views/pages/homepage.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#homepage</h1>
  <p>Find me in app/views/pages/homepage.html.erb</p>
  <div data-controller="hello" data-hello-hidden-class="hidden" data-hello-change-class="text-xl text-red-500" data-hello-hightlight-class="border-4 border-red"  >
    <%= button_tag "Add me", data: { action: 'click->hello#add'},  class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    <%= button_tag "Remove me", data: { action: 'click->hello#remove'},  class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    <%= button_tag "Toggle me", data: { action: 'click->hello#toggle'},  class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    <%# <%= button_tag "Toogle Drop Down ", data: { action: 'click->hello#toggle'},  class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %1> %>
    <div data-hello-target="text">
      <p> This Text can be Toggle  </p>
    </div>
    <div class="relative inline-block">
      <button data-action="click->hello#dropdowntoggle", class="bg-white rounded border border-gray-400
        py-2 px-4 text-gray-700 hover:text-gray-900
        hover:bg-gray-100 focus:outline-none focus:shadow-outline">
        Dropdown
      </button>
      <ul data-hello-target="dropdown" class="absolute hidden bg-white rounded border 
    border-gray-400 py-2 px-4 text-gray-700 mt-1 z-50
    divide-y divide-gray-400 right-0 w-48">
        <div class="flex flex-row align-center justify-center">
          <li data-action="click->hello#hideandshow"  class="flex-1 block px-2 py-2 text-gray-800 hover:bg-gray-100">Option 1</li>
          <input data-action="click->hello#highlight"  data-action="click->hello#hideandshow" type="checkbox" class="form-checkbox text-indigo-600 bg-gray-100 focus:shadow-outline-indigo focus:border-indigo-500 self-center" />
        </div>
        <li class="block px-2 py-2 text-gray-800 hover:bg-gray-100">Option 2</li>
        <li class="block px-2 py-2 text-gray-800 hover:bg-gray-100">Option 3</li>
        <li data-hello-target="hiddenelement" class="block px-2 py-2 text-gray-800 hover:bg-gray-100 hidden">Option 4</li>
      </ul>
    </div>
  </div>
  <div data-controller="text" data-text-max-value=280 data-text-over-class="text-red-600">
    <textarea data-action="text#updatecounter" data-text-target="field" id="tweetInput" rows="5"></textarea>
    <p data-text-target="showlength"></p>
  </div>
  <div>
    <div data-controller="car-selection">
      <%= form_with model: @car, url: pages_path, method: :post do |form| %>
        <%= form.label :model %>
        <%= form.select :model, @models , { prompt: "Select a country" }, { class: '', data: { action: "change->car-selection#selectmodel" } } %>
        <%= form.label :color %>
        <%= form.select :color, [], {}, {class: "", data: {car_selection_target: "colorSelect"} } %>
        <%= form.label :year %>
        <%= form.number_field :year, in: 1901..2021 %>
        <%= fields_for :variants_attributes do |v| %>
            <%= v.check_box :_destroy %>
            <%= v.label "Fuel Type" %>
            <%= v.select :fuel_type,["petrol", "diesel", "electric"]   %>
            <%= v.label "Transmission" %>
            <%= v.select :transmission, ["manual", "automatic"]%>
          <%# <%= render "variant_form", car_variant: %1> %>
        <% end %>
        <%= form.submit %>
      <% end %>
    </div>
  </div>
</div>